[package]
name = "guardianofthewild"
version = "0.1.0"
edition = "2018"

[lib]
name = "gotw"
path = "src/lib.rs"

[[bin]]
name = "guardianofthewild"
path = "src/main.rs"

[dependencies.tokio]
version = "1"
features = ["rt", "macros", "net", "io-util"]
